#./start-norm.sh "back/1 short interlude 1min  Mary Fall 9-22-22 - 22 September 2022 - 01-38-33 PM.mp4"
#./start-norm.sh "back/8 I can't get started 45s.mov"
#./start-norm.sh "back/Chris and Shoshana.mov"
#./start-norm.sh "back/IMG_3655.MOV"
# ./start-norm.sh "back/IMG_4068.MOV"
./start-norm.sh "back/Love. Because.....mp4"
# ./start-norm.sh "back/PULPIT SLIDESHOW FINAL 2017 480p.mov"
# ./start-norm.sh "back/Test.mp4"
#./start-norm.sh "back/casey at the bat.MOV"
